### ISSUE TITLE
Github Templates

### ISSUE THREAD

**Issue by Quinn-Donnelly** [USM-ACM/acmBackend#6]
# ACM Website
## Issue Type
- [ ] Bug
- [x] Feaure
## Description
Pull in the .github folder from the front end repository and edit it such that it makes sense in context with the back end (it may not need changes). This folder has the issue and PR templates inside of it and will help enforce guidelines. 

When done request review from @wrejcodes and @Quinn-Donnelly

**Comment by tctcodes** [comment]
@Quinn-Donnelly Just wanted to chime in.  I'm aware of my assignment to this issue, and I'm going to do it today.

**Comment by Quinn-Donnelly** [comment]
Thanks for the update! @timthom64 Keep up the great work. I appreciate the maintenance you are doing on the issues.

**Comment by tctcodes** [comment]
Closing issue because this was taken care of with the add dotgithub pull request from last week.
